# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe8be6d346fcc41f43f445a2636d0ad6352ceb4e43f15124bba755e8c98c24d269591827701ccd408c52450fdf88a8c870c15a5ea3fefd106b8f9e88d2ec009

test:
  secret_key_base: 671d10691905a02bf9adf46b8af5adcbfbd73db30ffd37291facef290d6bf1f733493cc0b18a220feffc9de408c032ea5edca654ee735647120bf91bc042d0ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
